### ISSUE TITLE
Terminates immediatly after start

### ISSUE THREAD

**Issue by emdete** [HenriDellal/emerald-dialer#21]
Since some days the dialer cant be used anymore, it terminates after started (screen shown for a short time). This is the only exception i can find in the logcat during that phase:

```
10-03 13:04:09.223  1928 25025 E DatabaseUtils: Writing exception to parcel
10-03 13:04:09.223  1928 25025 E DatabaseUtils: java.lang.IllegalArgumentException: URI: content://com.android.contacts/phone_lookup/, calling user: ru.henridellal.dialer, calling package:ru.henridellal.dialer
10-03 13:04:09.223  1928 25025 E DatabaseUtils: 	at com.android.providers.contacts.LegacyApiSupport.query(LegacyApiSupport.java:1855)
10-03 13:04:09.223  1928 25025 E DatabaseUtils: 	at com.android.providers.contacts.ContactsProvider2.queryLocal(ContactsProvider2.java:9882)
10-03 13:04:09.223  1928 25025 E DatabaseUtils: 	at com.android.providers.contacts.ContactsProvider2.queryDirectoryIfNecessary(ContactsProvider2.java:7793)
10-03 13:04:09.223  1928 25025 E DatabaseUtils: 	at com.android.providers.contacts.ContactsProvider2.query(ContactsProvider2.java:7750)
10-03 13:04:09.223  1928 25025 E DatabaseUtils: 	at android.content.ContentProvider.query(ContentProvider.java:1147)
10-03 13:04:09.223  1928 25025 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:240)
10-03 13:04:09.223  1928 25025 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
10-03 13:04:09.223  1928 25025 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:698)
10-03 13:04:09.223 11684 11701 E AndroidRuntime: FATAL EXCEPTION: Thread-4
10-03 13:04:09.223 11684 11701 E AndroidRuntime: Process: ru.henridellal.dialer, PID: 11684
10-03 13:04:09.223 11684 11701 E AndroidRuntime: java.lang.IllegalArgumentException: URI: content://com.android.contacts/phone_lookup/, calling user: ru.henridellal.dialer, calling package:ru.henridellal.dialer
10-03 13:04:09.223 11684 11701 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
10-03 13:04:09.223 11684 11701 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
10-03 13:04:09.223 11684 11701 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
10-03 13:04:09.223 11684 11701 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:769)
10-03 13:04:09.223 11684 11701 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:719)
10-03 13:04:09.223 11684 11701 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:670)
10-03 13:04:09.223 11684 11701 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader.loadImageForNumber(AsyncContactImageLoader.java:68)
10-03 13:04:09.223 11684 11701 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader$2.run(AsyncContactImageLoader.java:111)
10-03 13:04:09.223 11684 11701 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:809)
10-03 13:04:09.223 11684 11701 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-03 13:04:09.223 11684 11701 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
10-03 13:04:09.223 11684 11701 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader$BackgroundImageLoader.run(AsyncContactImageLoader.java:31)
10-03 13:04:09.225  1063  4787 W ActivityManager:   Force finishing activity ru.henridellal.dialer/.DialerActivity
```

i have no clue what's wrong. another dialer fails same way, the default dialer works fine. mobile is a Huawei P20 with standard firmware (but no google account or such).

**Comment by namjmnam** [comment]
Happened to me too. It appears that whenever there's an entry of empty number(or unknown number) in call log, it fails to display it and crash. (Sometimes you get calls that doesn't show their numbers)

**Comment by sefernet** [comment]
Relate #23

**Comment by puppykickr** [comment]
@namjmnam

Thank you so much for this info!
Reenabled my stock phone app just for the purpose of eliminating no number calls.

It appears that the problem can be caused by both incoming and outgoing calls as well.

I mistakenly tried to place a call while in airplane mode, and got stuck with Emerald turning off immediately after launch.

I love the app, minus this little glitch.

**Comment by Cocosushi6** [comment]
Same issue here, on a rooted Huawei P8 lite, running Android 7.0 with EMUI 5.0.
Apart from that, the app is quite cool :)

**Comment by kkr86** [comment]
> 
> 
> Same issue here, on a rooted Huawei P8 lite, running Android 7.0 with EMUI 5.0.
> Apart from that, the app is quite cool :)

same here (Huawei P8 lite, Android 6, EMUI 4.1.1, rooted)

**Comment by Rik44444** [comment]
same problem here
