### ISSUE TITLE
Feature request: GSM codes

### ISSUE THREAD

**Issue by JonnyTech** [HenriDellal/emerald-dialer#22]
Is it possible to handle so-called "GSM" or "secret" codes? These are numbers such as `*#06#` for IMEI details and `*#*#4636#*#*` for MediaTek testing mode access, to name just two of many. These codes work with stock dialers.

**Comment by sefernet** [comment]
Strange... Its works for me: Motorola, Android 6.0.1, ver. 1.0.4

**Comment by JonnyTech** [comment]
Maybe it is due to Android version or is ROM specific. I am running stock 8.0 ROM on a Nokia 3. Even setting Emerald Dialer to the default system dialer app does not acknowledge the dialled codes.

**Comment by JonnyTech** [comment]
Thanks for the update, the IMEI code now works but any other secret code causes a forced close crash. Does the app create logs?

**Comment by HenriDellal** [comment]
It's possible to get logs with adb (Android Debug Bridge).
[How to capture logs]{https://gsantner.net/android-contribution-guide/?packageid=ru.henridellal.emerald&name=Emerald%20Dialer&web=https://github.com/HenriDellal/emerald}

**Comment by HenriDellal** [comment]
It's possible to get logs with adb (Android Debug Bridge).
[How to capture logs]{https://gsantner.net/android-contribution-guide/?packageid=ru.henridellal.emerald&name=Emerald%20Dialer&web=https://github.com/HenriDellal/emerald}

**Comment by JonnyTech** [comment]
Thanks, log of starting app through to crash below:

```
11-17 21:32:38.662 I/ActivityManager(1044): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=ru.henridellal.dialer/.DialerActivity bnds=[155,568][292,761] (has extras)} from uid 10186
11-17 21:32:38.694 D/ViewRootImpl[dialer](1044): hardware acceleration is disabled, fakeHwAccelerated = true, HardwareRenderer.sRendererDisabled = false, forceHwAccelerated = false, HardwareRenderer.sSystemRendererDisabled = false, this = ViewRoot{99e01f9 Splash Screen ru.henridellal.dialer,ident = 1445}
11-17 21:32:38.716 I/BufferQueueConsumer(437): [Splash Screen ru.henridellal.dialer#0](this:0x74961f1000,id:14307,api:0,p:-1,c:437) setConsumerName: Splash Screen ru.henridellal.dialer#0
11-17 21:32:38.717 I/BufferQueueConsumer(437): [Splash Screen ru.henridellal.dialer#0](this:0x74961f1000,id:14307,api:0,p:-1,c:437) setDefaultBufferSize: width=720 height=1280
11-17 21:32:38.738 I/BufferQueueProducer(437): [Splash Screen ru.henridellal.dialer#0](this:0x74961f1000,id:14307,api:2,p:1044,c:437) connect(P): api=2 producer=(1044:system_server) producerControlledByApp=false
11-17 21:32:38.738 I/ActivityManager(1044): Start proc 679:ru.henridellal.dialer/u0a235 for activity ru.henridellal.dialer/.DialerActivity
11-17 21:32:38.802 I/vendor.mediatek.hardware.power@1.1-impl(427): notifyAppState pack:ru.henridellal.dialer, act:ru.henridellal.dialer.DialerActivity, pid:679, state:1
11-17 21:32:38.802 V/WindowManager(1044): Set focused app to: AppWindowToken{6b3c4b5 token=Token{aed3caf ActivityRecord{f3c3c8e u0 ru.henridellal.dialer/.DialerActivity t2103}}} old focus=AppWindowToken{67a7ae5 token=Token{fbe6bb9 ActivityRecord{1af96b2 u0 ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.Launcher t1081}}} moveFocusNow=true
11-17 21:32:38.803 I/libPerfService(427): [perfNotifyAppState] foreground:ru.henridellal.dialer, pid:679
11-17 21:32:39.209 D/OpenGLRenderer(679): <ru.henridellal.dialer> is running.
11-17 21:32:39.224 D/ViewRootImpl[DialerActivity](679): hardware acceleration is enabled, this = ViewRoot{ef0dc38 ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity,ident = 0}
11-17 21:32:39.228 V/PhoneWindow(679): DecorView setVisiblity: visibility = 0, Parent = ViewRoot{ef0dc38 ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity,ident = 0}, this = DecorView@9a881e9[DialerActivity]
11-17 21:32:39.274 I/WindowManager(1044): Relayout Window{de4d56d u0 ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity}: oldVis=4 newVis=0 focusMayChange = true
11-17 21:32:39.279 I/BufferQueueConsumer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:0,p:-1,c:437) setConsumerName: ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0
11-17 21:32:39.280 I/BufferQueueConsumer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:0,p:-1,c:437) setDefaultBufferSize: width=720 height=1280
11-17 21:32:39.281 V/WindowManager(1044): Changing focus from null to Window{de4d56d u0 ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:2179 com.android.server.wm.Session.relayout:235 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:162 
11-17 21:32:39.282 D/WindowManager(1044): Input focus has changed to Window{de4d56d u0 ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity}
11-17 21:32:39.338 V/WindowManager(1044): Set focused app to: AppWindowToken{8153233 token=Token{928f731 ActivityRecord{4f427d8 u0 com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity t2103}}} old focus=AppWindowToken{6b3c4b5 token=Token{aed3caf ActivityRecord{f3c3c8e u0 ru.henridellal.dialer/.DialerActivity t2103}}} moveFocusNow=true
11-17 21:32:39.338 V/WindowManager(1044): findFocusedWindow: Reached focused app=AppWindowToken{8153233 token=Token{928f731 ActivityRecord{4f427d8 u0 com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity t2103}}} target=AppWindowToken{6b3c4b5 token=Token{aed3caf ActivityRecord{f3c3c8e u0 ru.henridellal.dialer/.DialerActivity t2103}}}
11-17 21:32:39.339 V/WindowManager(1044): Changing focus from Window{de4d56d u0 ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity} to null Callers=com.android.server.wm.WindowManagerService.setFocusedApp:2739 com.android.server.am.ActivityManagerService.setResumedActivityUncheckLocked:3330 com.android.server.am.ActivityStack.setResumedActivityLocked:2312 com.android.server.am.ActivityStack.minimalResumeActivityLocked:1115 
11-17 21:32:39.421 I/BufferQueueProducer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:1,p:679,c:437) connect(P): api=1 producer=(679:ru.henridellal.dialer) producerControlledByApp=true
11-17 21:32:39.461 V/WindowManager(1044): Set focused app to: AppWindowToken{6b3c4b5 token=Token{aed3caf ActivityRecord{f3c3c8e u0 ru.henridellal.dialer/.DialerActivity t2103}}} old focus=AppWindowToken{8153233 token=Token{928f731 ActivityRecord{4f427d8 u0 com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity t2103}}} moveFocusNow=true
11-17 21:32:39.462 V/WindowManager(1044): Changing focus from null to Window{de4d56d u0 ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity} Callers=com.android.server.wm.WindowManagerService.setFocusedApp:2739 com.android.server.am.ActivityManagerService.setResumedActivityUncheckLocked:3330 com.android.server.am.ActivityStack.setResumedActivityLocked:2312 com.android.server.am.ActivityStack.resumeTopActivityInnerLocked:2694 
11-17 21:32:39.462 D/WindowManager(1044): Input focus has changed to Window{de4d56d u0 ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity}
11-17 21:32:39.465 I/vendor.mediatek.hardware.power@1.1-impl(427): notifyAppState pack:ru.henridellal.dialer, act:ru.henridellal.dialer.DialerActivity, pid:679, state:1
11-17 21:32:39.466 I/libPerfService(427): [perfNotifyAppState] foreground:ru.henridellal.dialer, pid:679
11-17 21:32:39.568 V/PhoneWindow(679): DecorView setVisiblity: visibility = 0, Parent = ViewRoot{ef0dc38 ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity,ident = 0}, this = DecorView@9a881e9[DialerActivity]
11-17 21:32:39.651 I/BufferQueueProducer(437): [Splash Screen ru.henridellal.dialer#0](this:0x74961f1000,id:14307,api:2,p:1044,c:437) disconnect(P): api 2
11-17 21:32:39.651 I/BufferQueueConsumer(437): [Splash Screen ru.henridellal.dialer#0](this:0x74961f1000,id:14307,api:2,p:-1,c:437) getReleasedBuffers: returning mask 0xffffffffffffffff
11-17 21:32:39.666 I/BufferQueueConsumer(437): [Splash Screen ru.henridellal.dialer#0](this:0x74961f1000,id:14307,api:2,p:-1,c:-1) disconnect(C)
11-17 21:32:39.666 I/BufferQueue(437): [Splash Screen ru.henridellal.dialer#0](this:0x74961f1000,id:14307,api:2,p:-1,c:-1) ~BufferQueueCore
11-17 21:32:39.696 I/ContactsProvider(28660): PHONE_LOOKUP number=+447947189956 E164=+447947189956 normalized=+447947189956 callingAP==ru.henridellal.dialer
11-17 21:32:39.739 I/ContactsProvider(28660): PHONE_LOOKUP number=+447906572756 E164=+447906572756 normalized=+447906572756 callingAP==ru.henridellal.dialer
11-17 21:32:39.782 I/ContactsProvider(28660): PHONE_LOOKUP number=+447542466751 E164=+447542466751 normalized=+447542466751 callingAP==ru.henridellal.dialer
11-17 21:32:39.804 I/ContactsProvider(28660): PHONE_LOOKUP number=+447542466751 E164=+447542466751 normalized=+447542466751 callingAP==ru.henridellal.dialer
11-17 21:32:39.824 I/ContactsProvider(28660): PHONE_LOOKUP number=+447900802037 E164=+447900802037 normalized=+447900802037 callingAP==ru.henridellal.dialer
11-17 21:32:40.546 I/BufferQueueProducer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:1,p:679,c:437) queueBuffer: fps=13.83 dur=1012.59 max=609.05 min=11.32
11-17 21:32:41.550 I/BufferQueueProducer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:1,p:679,c:437) queueBuffer: fps=61.78 dur=1003.52 max=21.15 min=13.60
11-17 21:32:42.557 I/BufferQueueProducer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:1,p:679,c:437) queueBuffer: fps=61.56 dur=1007.19 max=21.00 min=13.56
11-17 21:32:43.563 I/BufferQueueProducer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:1,p:679,c:437) queueBuffer: fps=51.71 dur=1005.66 max=176.48 min=13.56
11-17 21:32:44.563 I/BufferQueueProducer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:1,p:679,c:437) queueBuffer: fps=60.95 dur=1000.87 max=31.08 min=10.44
11-17 21:32:45.566 I/BufferQueueProducer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:1,p:679,c:437) queueBuffer: fps=61.81 dur=1003.07 max=19.79 min=14.55
11-17 21:32:46.571 I/BufferQueueProducer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:1,p:679,c:437) queueBuffer: fps=53.77 dur=1004.21 max=146.51 min=12.51
11-17 21:32:47.575 I/BufferQueueProducer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:1,p:679,c:437) queueBuffer: fps=60.76 dur=1003.99 max=33.53 min=14.07
11-17 21:32:47.750 E/AndroidRuntime(679): Process: ru.henridellal.dialer, PID: 679
11-17 21:32:47.750 E/AndroidRuntime(679): 	at ru.henridellal.dialer.DialerActivity.onTextChanged(DialerActivity.java:463)
11-17 21:32:47.750 E/AndroidRuntime(679): 	at ru.henridellal.dialer.DialerActivity.addSymbolInNumber(DialerActivity.java:242)
11-17 21:32:47.750 E/AndroidRuntime(679): 	at ru.henridellal.dialer.DialerActivity.onClick(DialerActivity.java:154)
11-17 21:32:47.759 W/ActivityManager(1044):   Force finishing activity ru.henridellal.dialer/.DialerActivity
11-17 21:32:47.777 D/AES     (1044): onEndOfErrorDumpThread: data_app_crash Process: ru.henridellal.dialer
11-17 21:32:47.777 D/AES     (1044): Package: ru.henridellal.dialer v7 (1.0.5)
11-17 21:32:47.777 D/AES     (1044): 	at ru.henridellal.dialer.DialerActivity.onTextChanged(DialerActivity.java:463)
11-17 21:32:47.777 D/AES     (1044): 	at ru.henridellal.dialer.DialerActivity.addSymbolInNumber(DialerActivity.java:242)
11-17 21:32:47.777 D/AES     (1044): 	at ru.henridellal.dialer.DialerActivity.onClick(DialerActivity.java:154)
11-17 21:32:47.783 D/AES     (1044):     process : ru.henridellal.dialer
11-17 21:32:47.783 D/AES     (1044):      module : ru.henridellal.dialer v7 (1.0.5)
11-17 21:32:47.783 D/AEE_LIBAEE(1044): shell: raise_exp(4, 679, -1361051648, ru.henridellal.dialer, 0x0x73091c39e0, 0x0x0)
11-17 21:32:47.786 I/ActivityManager(1044): Showing crash dialog for package ru.henridellal.dialer u0
11-17 21:32:47.799 I/AEE_AED (832): [preset_info] pid: 679, tid: -1361051648, name: UNKNOWN  >>> ru.henridellal.dialer <<<
11-17 21:32:47.800 V/AEE_AED (832): dashboard_record_update() : rec->module = ru.henridellal.dialer 
11-17 21:32:47.939 D/ViewRootImpl[dialer](1044): hardware acceleration is enabled, this = ViewRoot{ebaaaa4 Application Error: ru.henridellal.dialer,ident = 1446}
11-17 21:32:47.942 V/WindowManager(1044): Changing focus from Window{de4d56d u0 ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity} to Window{d476009 u0 Application Error: ru.henridellal.dialer} Callers=com.android.server.wm.WindowManagerService.addWindow:1587 com.android.server.wm.Session.addToDisplay:200 android.view.ViewRootImpl.setView:840 android.view.WindowManagerGlobal.addView:361 
11-17 21:32:47.944 D/WindowManager(1044): Input focus has changed to Window{d476009 u0 Application Error: ru.henridellal.dialer}
11-17 21:32:47.964 I/StabilityMonitor(26805): [ParserUtility] key word : ru.henridellal.dialer
11-17 21:32:47.966 I/BufferQueueConsumer(437): [Application Error: ru.henridellal.dialer#0](this:0x7496e51800,id:14309,api:0,p:-1,c:437) setConsumerName: Application Error: ru.henridellal.dialer#0
11-17 21:32:47.967 I/BufferQueueConsumer(437): [Application Error: ru.henridellal.dialer#0](this:0x7496e51800,id:14309,api:0,p:-1,c:437) setDefaultBufferSize: width=812 height=419
11-17 21:32:47.968 I/StabilityMonitor(26805): [APRReport] exceptionItem  tag:data_app_crash packageName:ru.henridellal.dialer versionCode:7 versionName:1.0.5
11-17 21:32:48.003 I/BufferQueueProducer(437): [Application Error: ru.henridellal.dialer#0](this:0x7496e51800,id:14309,api:1,p:1044,c:437) connect(P): api=1 producer=(1044:system_server) producerControlledByApp=false
11-17 21:32:48.038 E/STBIntentService(26805): send error message:data_app_crash;1542490367776(pkgName:ru.henridellal.dialer;version:1.0.5;versionCode:7) to BBS for ANR/FC/TOMB_STONE...
11-17 21:32:48.068 I/WindowManager(1044): Losing delayed focus: Window{de4d56d u0 ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity}
11-17 21:32:48.264 W/ActivityManager(1044): Activity pause timeout for ActivityRecord{f3c3c8e u0 ru.henridellal.dialer/.DialerActivity t2103 f}
11-17 21:32:48.267 V/WindowManager(1044): Set focused app to: AppWindowToken{67a7ae5 token=Token{fbe6bb9 ActivityRecord{1af96b2 u0 ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.Launcher t1081}}} old focus=AppWindowToken{6b3c4b5 token=Token{aed3caf ActivityRecord{f3c3c8e u0 ru.henridellal.dialer/.DialerActivity t2103}}} moveFocusNow=true
11-17 21:32:48.440 I/SurfaceFlinger(437): screenshot (ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0)
11-17 21:32:50.761 W/ActivityManager(1044):   Force finishing activity ru.henridellal.dialer/.DialerActivity
11-17 21:32:50.765 I/BufferQueueProducer(437): [Application Error: ru.henridellal.dialer#0](this:0x7496e51800,id:14309,api:1,p:1044,c:437) disconnect(P): api 1
11-17 21:32:50.765 I/BufferQueueConsumer(437): [Application Error: ru.henridellal.dialer#0](this:0x7496e51800,id:14309,api:1,p:-1,c:437) getReleasedBuffers: returning mask 0xffffffffffffffff
11-17 21:32:50.773 I/BufferQueueConsumer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:1,p:679,c:-1) disconnect(C)
11-17 21:32:50.776 V/WindowManager(1044): Remove Window{d476009 u0 Application Error: ru.henridellal.dialer} client=349cd10, surfaceController=Surface(name=Application Error: ru.henridellal.dialer) Callers=com.android.server.wm.WindowState.removeIfPossible:1771 com.android.server.wm.WindowManagerService.removeWindow:1754 com.android.server.wm.Session.remove:219 android.view.ViewRootImpl.dispatchDetachedFromWindow:3915 android.view.ViewRootImpl.doDie:6868 
11-17 21:32:50.779 V/WindowManager(1044): Changing focus from Window{d476009 u0 Application Error: ru.henridellal.dialer EXITING} to Window{ab0ac78 u0 ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.Launcher} Callers=com.android.server.wm.WindowState.setupWindowForRemoveOnExit:1919 com.android.server.wm.WindowState.removeIfPossible:1891 com.android.server.wm.WindowState.removeIfPossible:1771 com.android.server.wm.WindowManagerService.removeWindow:1754 
11-17 21:32:50.793 I/ActivityManager(1044): Killing 679:ru.henridellal.dialer/u0a235 (adj 902): crash
11-17 21:32:50.943 I/BufferQueueProducer(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:1,p:679,c:-1) disconnect(P): api 1
11-17 21:32:50.944 I/BufferQueue(437): [ru.henridellal.dialer/ru.henridellal.dialer.DialerActivity#0](this:0x74961f5800,id:14308,api:1,p:-1,c:-1) ~BufferQueueCore
11-17 21:32:50.984 I/BufferQueueConsumer(437): [Application Error: ru.henridellal.dialer#0](this:0x7496e51800,id:14309,api:1,p:-1,c:-1) disconnect(C)
11-17 21:32:50.984 I/BufferQueue(437): [Application Error: ru.henridellal.dialer#0](this:0x7496e51800,id:14309,api:1,p:-1,c:-1) ~BufferQueueCore
```

**Comment by HenriDellal** [comment]
Thank you. I can see where the crash happens, but I don't know the reason, because the system doesn't provide information about the exception. I can't promise to fix it, but I'll try to.

**Comment by JonnyTech** [comment]
Thanks, let me know if I can help with debugging.

**Comment by DJCrashdummy** [comment]
although it is not really important i have to report, that on a dual-SIM phone just the first IMEI is shown.

**Comment by HenriDellal** [comment]
I have to use a custom function in order to get an IMEI, so it is expected, but I'd like to fix it as well.

**Comment by neekless** [comment]
Does this help? https://del.dog/iyifugupid.pl
