### ISSUE TITLE
crash when closing dial pad in Oero

### ISSUE THREAD

**Issue by roytam1** [HenriDellal/emerald-dialer#60]
App Version: 1.0.8 from F-Droid

Phone: SONY Xperia XZ1 Compact, Android 8.0

logcat from bugreport*.zip
````
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: Process: ru.henridellal.dialer, PID: 8741
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.SemcContactsProvider2 from ProcessRecord{8d1edb5 8741:ru.henridellal.dialer/u0a254} (pid=8741, uid=10254) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1960)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1899)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4771)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:5913)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2498)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1783)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:740)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:705)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.content.CursorLoader.loadInBackground(CursorLoader.java:64)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.content.CursorLoader.loadInBackground(CursorLoader.java:54)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:315)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:64)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-22 16:09:31.729 10254  8741  8762 E AndroidRuntime: 	... 3 more
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: Process: ru.henridellal.dialer, PID: 8741
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.SemcCallLogProvider from ProcessRecord{8d1edb5 8741:ru.henridellal.dialer/u0a254} (pid=8741, uid=10254) requires android.permission.READ_CALL_LOG or android.permission.WRITE_CALL_LOG
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1960)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1899)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4771)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:5913)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2498)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1783)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:740)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:705)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.content.CursorLoader.loadInBackground(CursorLoader.java:64)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.content.CursorLoader.loadInBackground(CursorLoader.java:54)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:315)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:64)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-22 16:09:31.729 10254  8741  8761 E AndroidRuntime: 	... 3 more
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: FATAL EXCEPTION: Thread-2
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: Process: ru.henridellal.dialer, PID: 8778
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: java.lang.IllegalArgumentException: URI: content://com.android.contacts/phone_lookup/, calling user: ru.henridellal.dialer, calling package:ru.henridellal.dialer
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:756)
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:705)
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:663)
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader.loadImageForNumber(AsyncContactImageLoader.java:71)
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader$2.run(AsyncContactImageLoader.java:114)
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:251)
08-22 16:10:05.669 10254  8778  8796 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader$BackgroundImageLoader.run(AsyncContactImageLoader.java:31)
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: FATAL EXCEPTION: Thread-2
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: Process: ru.henridellal.dialer, PID: 8922
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: java.lang.IllegalArgumentException: URI: content://com.android.contacts/phone_lookup/, calling user: ru.henridellal.dialer, calling package:ru.henridellal.dialer
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:756)
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:705)
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:663)
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader.loadImageForNumber(AsyncContactImageLoader.java:71)
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader$2.run(AsyncContactImageLoader.java:114)
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:251)
08-22 16:10:09.225 10254  8922  8939 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader$BackgroundImageLoader.run(AsyncContactImageLoader.java:31)
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: FATAL EXCEPTION: Thread-2
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: Process: ru.henridellal.dialer, PID: 8978
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: java.lang.IllegalArgumentException: URI: content://com.android.contacts/phone_lookup/, calling user: ru.henridellal.dialer, calling package:ru.henridellal.dialer
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:756)
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:705)
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:663)
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader.loadImageForNumber(AsyncContactImageLoader.java:71)
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader$2.run(AsyncContactImageLoader.java:114)
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:251)
08-22 16:10:16.017 10254  8978  8997 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader$BackgroundImageLoader.run(AsyncContactImageLoader.java:31)
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: FATAL EXCEPTION: Thread-2
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: Process: ru.henridellal.dialer, PID: 9039
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: java.lang.IllegalArgumentException: URI: content://com.android.contacts/phone_lookup/, calling user: ru.henridellal.dialer, calling package:ru.henridellal.dialer
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:756)
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:705)
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:663)
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader.loadImageForNumber(AsyncContactImageLoader.java:71)
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader$2.run(AsyncContactImageLoader.java:114)
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:251)
08-22 16:10:30.193 10254  9039  9057 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader$BackgroundImageLoader.run(AsyncContactImageLoader.java:31)
08-22 16:21:22.796 10024 10226 10328 E DatabaseUtils: Writing exception to parcel
08-22 16:21:22.796 10024 10226 10328 E DatabaseUtils: java.lang.IllegalArgumentException: URI: content://com.android.contacts/phone_lookup/, calling user: ru.henridellal.dialer, calling package:ru.henridellal.dialer
08-22 16:21:22.796 10024 10226 10328 E DatabaseUtils: 	at com.android.providers.contacts.LegacyApiSupport.query(LegacyApiSupport.java:1836)
08-22 16:21:22.796 10024 10226 10328 E DatabaseUtils: 	at com.android.providers.contacts.ContactsProvider2.queryLocal(ContactsProvider2.java:7296)
08-22 16:21:22.796 10024 10226 10328 E DatabaseUtils: 	at com.android.providers.contacts.ContactsProvider2.queryDirectoryIfNecessary(ContactsProvider2.java:5702)
08-22 16:21:22.796 10024 10226 10328 E DatabaseUtils: 	at com.android.providers.contacts.ContactsProvider2.query(ContactsProvider2.java:5681)
08-22 16:21:22.796 10024 10226 10328 E DatabaseUtils: 	at com.android.providers.contacts.SemcContactsProvider2.query(SemcContactsProvider2.java:550)
08-22 16:21:22.796 10024 10226 10328 E DatabaseUtils: 	at android.content.ContentProvider.query(ContentProvider.java:1149)
08-22 16:21:22.796 10024 10226 10328 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:242)
08-22 16:21:22.796 10024 10226 10328 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
08-22 16:21:22.796 10024 10226 10328 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:674)
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: FATAL EXCEPTION: Thread-3
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: Process: ru.henridellal.dialer, PID: 10927
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: java.lang.IllegalArgumentException: URI: content://com.android.contacts/phone_lookup/, calling user: ru.henridellal.dialer, calling package:ru.henridellal.dialer
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:756)
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:705)
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:663)
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader.loadImageForNumber(AsyncContactImageLoader.java:71)
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader$2.run(AsyncContactImageLoader.java:114)
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:251)
08-22 16:21:22.796 10263 10927 11202 E AndroidRuntime: 	at ru.henridellal.dialer.AsyncContactImageLoader$BackgroundImageLoader.run(AsyncContactImageLoader.java:31)

````

**Comment by HenriDellal** [comment]
Fixed in 0a0ab75
