### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by islam2hamy** [HenriDellal/emerald-dialer#90]
FATAL EXCEPTION: main
Process: ru.henridellal.dialer, PID: 19937
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
	at ru.henridellal.dialer.util.RTLUtil.format(RTLUtil.java:10)
	at ru.henridellal.dialer.LogEntryAdapter.bindView(LogEntryAdapter.java:155)
	at android.widget.CursorAdapter.getView(CursorAdapter.java:296)
	at android.widget.AbsListView.obtainView(AbsListView.java:2516)
	at android.widget.ListView.makeAndAddView(ListView.java:2065)
	at android.widget.ListView.fillDown(ListView.java:791)
	at android.widget.ListView.fillGap(ListView.java:754)
	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5693)
	at android.widget.ListView.trackMotionScroll(ListView.java:1982)
	at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:5218)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1624)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1633)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1168)
	at android.view.Choreographer.doFrame(Choreographer.java:1068)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1597)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8720)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by HenriDellal** [comment]
Thank you for feedback, the fix will be available in the next release.

**Comment by islam2hamy** [comment]
Thank You
Nice App
